/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Test.java
 *
 * Created on Feb 9, 2012, 2:35:10 AM
 */
package miRNAData;

import BLASTGrabber.Facade.BLASTGrabberHit;
import BLASTGrabber.Facade.BLASTGrabberQuery;

import java.util.*;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreeModel;

/**
 *
 * @author Petter
 */


public class Test extends javax.swing.JInternalFrame implements TreeSelectionListener{
    
    private HashMap<String, BLASTGrabberQuery> queries;
    
    
    /** Creates new form Test */
    public Test(HashMap queries) {
        initComponents();
        this.queries = queries;
        makeNodes();
    }
    
    private void makeNodes(){
        DefaultMutableTreeNode top = new DefaultMutableTreeNode();
        Iterator<String> queryIterator = queries.keySet().iterator();
        Iterator<String> hitIterator;
        BLASTGrabberQuery currentQuery;
        String queryKey;
        DefaultMutableTreeNode queryNode, hitNode;
        
        while(queryIterator.hasNext()){
            queryKey = queryIterator.next();
            currentQuery = queries.get(queryKey);
            queryNode = new DefaultMutableTreeNode(currentQuery);
            top.add(queryNode);
            for(BLASTGrabberHit hit : currentQuery.Hits){
                hitNode = new DefaultMutableTreeNode(hit);
                queryNode.add(hitNode);
                
            }
        }
        
        TreeModel tm = new DefaultTreeModel(top);
        jTree1.setModel(tm);
        jTree1.addTreeSelectionListener(this);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTextField1.setText("jTextField1");

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(TreeSelectionEvent e) {
        Object currentNode = jTree1.getLastSelectedPathComponent();
        jTextField1.setText(currentNode.toString());
    }
}
