/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * miRNATreeStrucutre.java
 *
 * Created on Feb 9, 2012, 1:54:32 AM
 */
package miRNAData;

import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import java.util.HashMap;
import BLASTGrabber.Facade.BLASTGrabberHit;
import BLASTGrabber.Facade.BLASTGrabberQuery;
import java.util.Iterator;

/**
 *
 * @author Petter
 */
public class TreePanel extends javax.swing.JPanel {
    
    HashMap<String, miRNAQuery> queries;

    /** Creates new form miRNATreeStrucutre */
    public TreePanel() {      
        initComponents();
        makeNodes();
    }
    
    public void setQueries(HashMap<String, miRNAQuery> queries){
        this.queries = queries;
    }
    
    
    
    
    private void makeNodes(){
        
        ArrayList<DefaultMutableTreeNode> queryNodes = new ArrayList<DefaultMutableTreeNode>();

        
        DefaultMutableTreeNode top = new DefaultMutableTreeNode();
        
        Iterator<String> queryIterator = queries.keySet().iterator();
        
        miRNAQuery currentQuery;
        while(queryIterator.hasNext()){
            currentQuery = queries.get(queryIterator.next());
            top.add(new DefaultMutableTreeNode(currentQuery));
        }

        
        TreeModel tm = new DefaultTreeModel(top);
        hitTree.setModel(tm);
        
    }
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hitTree = new javax.swing.JTree();

        hitTree.setRootVisible(false);
        jScrollPane1.setViewportView(hitTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree hitTree;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
